name=DCCppEX
version=1.0.0
author=Thierry Paris - Locoduino
maintainer=Thierry Paris - Locoduino
sentence=This is a library to control DCC devices.
paragraph=Library version of the CommanderStation++EX work from DCC++EX group
category=Device Control
url=https://github.com/Locoduino/DCCpp
architectures=avr
